name: Tests
on: [push, pull_request]

jobs:
  test:
    name: Test Workspace on AMD64 Rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        rust: [stable]
    container:
      image: ${{ matrix.arch }}/rust
      env:
        # Disable full debug symbol generation to speed up CI build and keep memory down
        # "1" means line tables only, which is useful for panic tracebacks.
        RUSTFLAGS: "-C debuginfo=1"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: /home/runner/.cargo
          key: cargo-cache-
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: /home/runner/target
          key: target-cache-
      - name: Setup Rust toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
          rustup component add rustfmt
          rustup component add clippy
          apt update
          apt install -y clang
      - name: Run tests
        run: |
          cargo test
      - name: Run format
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --workspace -- -D warnings

